// ============================================================================
//
// Copyright (C) 2006-2017 Talend Inc. - www.talend.com
//
// This source code is available under agreement available at
// %InstallDIR%\features\org.talend.rcp.branding.%PRODUCTNAME%\%PRODUCTNAME%license.txt
//
// You should have received a copy of the agreement
// along with this program; if not, write to Talend SA
// 9 rue Pages 92150 Suresnes, France
//
// ============================================================================
package org.talend.components.simplefileio.runtime.s3;

import static org.hamcrest.Matchers.containsInAnyOrder;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.hasSize;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.nullValue;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertThat;
import static org.talend.components.test.RecordSetUtil.getSimpleTestData;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import org.apache.avro.Schema;
import org.apache.avro.Schema.Field;
import org.apache.avro.generic.IndexedRecord;
import org.apache.beam.sdk.testing.TestPipeline;
import org.apache.beam.sdk.transforms.Create;
import org.apache.beam.sdk.values.PCollection;
import org.apache.commons.lang.StringUtils;
import org.junit.ClassRule;
import org.junit.Ignore;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TestRule;
import org.talend.components.adapter.beam.transform.DirectCollector;
import org.talend.components.simplefileio.SimpleFileIODatasetProperties;
import org.talend.components.simplefileio.SimpleFileIOFormat;
import org.talend.components.simplefileio.runtime.SimpleFileIODatasetRuntime;
import org.talend.components.simplefileio.s3.S3DatasetProperties;
import org.talend.components.simplefileio.s3.S3DatastoreProperties;
import org.talend.components.simplefileio.s3.input.S3InputProperties;
import org.talend.components.simplefileio.s3.output.S3OutputProperties;
import org.talend.components.test.DisableIfMissingConfig;
import org.talend.components.test.RecordSet;
import org.talend.daikon.java8.Consumer;

import com.talend.shaded.com.amazonaws.services.s3.model.ObjectMetadata;

/**
 * Unit tests for {@link S3InputRuntime} and {@link S3OutputRuntime}, focusing on the use cases where data is written by
 * an output component, and then read by an input component.
 *
 * The input component should be able to read all files generated by the output component.
 */
public class S3RoundTripRuntimeTestIT {
	
	/*
    @ClassRule
    public static final TestRule DISABLE_WHEN_NEEDED = new DisableIfMissingConfig("s3.accesskey");
    */

    @Rule
    public TestPipeline pWrite = TestPipeline.create();

    @Rule
    public TestPipeline pRead = TestPipeline.create();

    /** Set up credentials for integration tests. */
    @Rule
    public S3TestResource s3 = S3TestResource.of();

    /**
     * Tests a round-trip on the data when writing to the data source using the given output properties, then
     * subsequently reading using the given input properties. This is the equivalent of two pipeline jobs.
     *
     * @param initialData The initial data set to write, then read.
     * @param outputProps The properties used to create the output runtime.
     * @param inputProps The properties used to create the input runtime.
     * @return The data returned from the round-trip.
     */
    protected List<IndexedRecord> runRoundTripPipelines(List<IndexedRecord> initialData, S3OutputProperties outputProps,
            S3InputProperties inputProps) {
        // Create the runtimes.
        S3OutputRuntime outputRuntime = new S3OutputRuntime();
        outputRuntime.initialize(null, outputProps);
        S3InputRuntime inputRuntime = new S3InputRuntime();
        inputRuntime.initialize(null, inputProps);

        // Create a pipeline to write the records to the output.
        {
            PCollection<IndexedRecord> input = pWrite.apply(Create.<IndexedRecord> of(initialData));
            input.apply(outputRuntime);
            pWrite.run().waitUntilFinish();
        }

        // Read the records that were written.
        try (DirectCollector<IndexedRecord> collector = DirectCollector.of()) {
            PCollection<IndexedRecord> input = pRead.apply(inputRuntime);
            input.apply(collector);
            pRead.run().waitUntilFinish();

            // Return the list of records from the round trip.
            return collector.getRecords();
        }
    }

    protected List<IndexedRecord> getSample(S3DatasetProperties datasetProperties) {
        S3DatasetRuntime datasetRuntime = new S3DatasetRuntime();
        datasetRuntime.initialize(null, datasetProperties);
        final List<IndexedRecord> samples = new ArrayList<>();
        datasetRuntime.getSample(10, new Consumer<IndexedRecord>() {

            @Override
            public void accept(IndexedRecord indexedRecord) {
                samples.add(indexedRecord);
            }
        });
        return samples;
    }

    protected Schema getSchema(S3DatasetProperties datasetProperties) {
        S3DatasetRuntime datasetRuntime = new S3DatasetRuntime();
        datasetRuntime.initialize(null, datasetProperties);
        return datasetRuntime.getSchema();
    }

    public void test_noEncryption(S3DatasetProperties datasetProps) throws IOException {
        // The file that we will be creating.
        RecordSet rs = getSimpleTestData(0);

        // Configure the components.
        S3OutputProperties outputProps = new S3OutputProperties("out");
        outputProps.setDatasetProperties(datasetProps);
        S3InputProperties inputProps = new S3InputProperties("in");
        inputProps.setDatasetProperties(datasetProps);

        List<IndexedRecord> actual = runRoundTripPipelines(rs.getAllData(), outputProps, inputProps);

        List<IndexedRecord> expected = rs.getAllData();
        assertThat(actual, containsInAnyOrder(expected.toArray()));

        List<IndexedRecord> samples = getSample(datasetProps);
        assertThat(samples, containsInAnyOrder(expected.toArray()));

        Schema schema = getSchema(datasetProps);
        assertEquals(expected.get(0).getSchema(), schema);
    }

    /**
     * Basic Avro test.
     */
    @Test
    public void testAvro_noEncryption() throws IOException {
        S3DatasetProperties datasetProps = s3.createS3DatasetProperties();
        datasetProps.format.setValue(SimpleFileIOFormat.AVRO);
        test_noEncryption(datasetProps);

        // Get some object metadata from the results.
        ObjectMetadata md = s3.getObjectMetadata(datasetProps);
        assertThat(md.getSSEAlgorithm(), nullValue());
        assertThat(md.getSSEAwsKmsKeyId(), nullValue());
    }

    /**
     * Basic Csv test.
     */
    @Test
    @Ignore("columns name different, can't editable")
    public void testCsv_noEncryption() throws IOException {
        S3DatasetProperties datasetProps = s3.createS3DatasetProperties();
        datasetProps.format.setValue(SimpleFileIOFormat.CSV);
        datasetProps.recordDelimiter.setValue(SimpleFileIODatasetProperties.RecordDelimiterType.LF);
        datasetProps.fieldDelimiter.setValue(SimpleFileIODatasetProperties.FieldDelimiterType.SEMICOLON);
        datasetProps.headerLine.setValue(0);
        test_noEncryption(datasetProps);
    }

    /**
     * Basic Parquet test.
     */
    @Test
    public void testParquet_noEncryption() throws IOException {
        S3DatasetProperties datasetProps = s3.createS3DatasetProperties();
        datasetProps.format.setValue(SimpleFileIOFormat.PARQUET);
        test_noEncryption(datasetProps);
    }

    /**
     * Basic Avro test with sseKmsEncryption.
     */
    @Test
    public void testAvro_sseKmsEncryption() throws IOException {
        S3DatasetProperties datasetProps = s3.createS3DatasetProperties(true, false);
        datasetProps.format.setValue(SimpleFileIOFormat.AVRO);
        test_noEncryption(datasetProps);

        // Get some object metadata from the results.
        ObjectMetadata md = s3.getObjectMetadata(datasetProps);
        assertThat(md.getSSEAlgorithm(), is("aws:kms"));
        assertThat(md.getSSEAwsKmsKeyId(), is(datasetProps.kmsForDataAtRest.getValue()));
    }

    /**
     * Basic Avro test with cseKmsEncryption.
     */
    @Ignore("cse not yet supported.")
    @Test
    public void testAvro_cseKmsEncryption() throws IOException {
        S3DatasetProperties datasetProps = s3.createS3DatasetProperties(false, true);
        datasetProps.format.setValue(SimpleFileIOFormat.AVRO);
        test_noEncryption(datasetProps);
    }

    /**
     * Basic Avro test with sseKmsEncryption.
     */
    @Ignore("cse not yet supported.")
    @Test
    public void testAvro_sseAndCseKmsEncryption() throws IOException {
        S3DatasetProperties datasetProps = s3.createS3DatasetProperties(true, true);
        datasetProps.format.setValue(SimpleFileIOFormat.AVRO);
        test_noEncryption(datasetProps);
    }
    
    @Test
    public void testBug() throws IOException {
        S3DatasetProperties properties = new S3DatasetProperties(null);
		properties.init();
		properties.bucket.setValue("wwang");
		properties.object.setValue("10L3C.csv");
		S3DatastoreProperties sp = new S3DatastoreProperties(null);
		sp.init();
		sp.accessKey.setValue("");
		sp.secretKey.setValue("");
		properties.setDatastoreProperties(sp);
		properties.format.setValue(SimpleFileIOFormat.CSV);
		properties.setHeaderLine.setValue(true);
		properties.headerLine.setValue(1);
		
		final List<IndexedRecord> actual = getSample(properties,100);

		assertThat(actual, hasSize(10));
        List<Field> fields = actual.get(0).getSchema().getFields();
        assertThat(fields, hasSize(3));
        
        assertThat("0", equalTo(actual.get(0).get(0)));
        assertThat("Adele", equalTo(actual.get(0).get(1)));
        assertThat("15/01/2017", equalTo(actual.get(0).get(2)));
        
        assertThat("9", equalTo(actual.get(9).get(0)));
        assertThat("Jenifer", equalTo(actual.get(9).get(1)));
        assertThat("15/10/2017", equalTo(actual.get(9).get(2)));
    }
    
    private List<IndexedRecord> getSample(S3DatasetProperties props, int limit) {
        // Create the runtime.
        S3DatasetRuntime runtime = new S3DatasetRuntime();
        runtime.initialize(null, props);

        // Attempt to get a sample using the runtime methods.
        final List<IndexedRecord> actual = new ArrayList<>();
        runtime.getSample(limit, new Consumer<IndexedRecord>() {

            @Override
            public void accept(IndexedRecord ir) {
                actual.add(ir);
            }
        });
        return actual;
      }
}
